### ISSUE TITLE
[Suggestion] adjust DPI for experimental Virtual Extended Display

### ISSUE THREAD

**Issue by CorruptionVR** [yume-chan/tango-feedback#1]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How would you like Tango to be improved?

I would like the ability to change the dpi of the Virtual extended display because the screen is too cramped. it just end up looking like this
![image](https://github.com/yume-chan/tango-feedback/assets/78228404/40a79ed7-101a-435a-bdd8-06ced3736c82)

### How do you think it should work?

add an input to change the DPI

**Comment by yume-chan** [comment]
Thanks for your suggestion! I have now added an input for virtual display density.

---

Note that due to offline cache, the following steps are required to see the new changes:

1. Open Tango
2. Wait for about 10 seconds for the new version to be downloaded
3. Close all tabs of Tango
4. Reopen Tango

This will be improved in the future.

**Comment by CorruptionVR** [comment]
thank you for the quick response
