### ISSUE TITLE
[Suggestion] [domain : scrcpy] unpin/hide button side bar

### ISSUE THREAD

**Issue by CorruptionVR** [yume-chan/tango-feedback#3]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How would you like Tango to be improved?

I would like the ability to hide or pin/unpin the button side bar with the back, home, recents and volume controls to be able to use the entire window for viewing

### How do you think it should work?

have a pin/unpin button on the bottom of the sidebar or have a hide/show toggle next to the stop button.

**Comment by CorruptionVR** [comment]
hey, thanks for adding the "show command bar" toggle, but could you add a picture in picture button next to stop or something so that I can enable it without the command bar?
edit: oh, also a fullscreen button

**Comment by yume-chan** [comment]
It needs a new design for hidden command bar mode, that's why I haven't closed this issue.

In the next step I will allow the command bar and the app switcher to be moved to all four sides of the screen display, and I'm considering adding an auto-hide mode where it reveals itself when mouse cursor is near window border.

**Comment by CorruptionVR** [comment]
oh, ok.

**Comment by CorruptionVR** [comment]
This has been added to the new web app.
